siteMetadata:
  siteName: Gumroad API Tester
  siteUrl: 'https://justinmahar.github.io/gumroad-api-tester-webapp'
  siteDescription: A webapp for easily testing the Gumroad API.
  siteIcon: /media/site-icon.png
  siteIconAlt: Cyclone
  siteImage: '{siteUrl}/media/site-image.png'
  siteImageWidth: 1200
  siteImageHeight: 600
  siteImageAlt: Repository information for project
gatsbyPluginManifestOptions:
  name: Gumroad API Tester
  shortName: Gumroad API
  startUrl: /
  themeColor: '#1167b1'
  backgroundColor: '#03254c'
  display: standalone
  customIcon: none # '/media/pwa-icon.png'
seoTitleFormat: '{contentTitle}{seoTitleSeparator}{siteName}' # See README for all template tags
seoTitleSeparator: ' - '
privatePagePathPrefix: private # Must not start or end with a slash
googleAnalyticsMeasurementId: none
twitterSiteUsername: none
redirects: # https://www.gatsbyjs.com/docs/reference/config-files/actions/#createRedirect
  - fromPath: /old-url
    toPath: /new-url
    isPermanent: true
